version: '3.9'
name: chatbot
services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code  # Sync local development directory with the container
    
    ports:
      - "8001:8000" 


  
networks:
  default:
    driver: bridge